#
# RaTOS Real-Time OS
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "ratos"
BBFILE_PATTERN_ratos = "^${LAYERDIR}/"
BBFILE_PRIORITY_ratos = "7"

LAYERSERIES_COMPAT_ratos = "next"

LAYERDIR_ratos = "${LAYERDIR}"
LAYERDIR_ratos[vardepvalue] = "ratos"
